version: "3.8"
services:
    mongo:
        container_name: mongodb
        networks:
            - shopping
        environment:
            - MONGO_INITDB_ROOT_USERNAME=max
            - MONGO_INITDB_ROOT_PASSWORD=secret
        volumes:
            - data:/data/db
        image: mongo
    shopping-backend:
        container_name: backend
        networks:
            - shopping
        ports:
            - 80:80
        volumes:
            - logs:/logs
            - node_modules:/node_modules
        image: orion87/shopping-backend
    shopping-frontend:
        container_name: frontend
        networks:
            - shopping
        ports:
            - 3000:3000
        volumes:
            - .\frontend\src:/src
        image: orion87/shopping-frontend
networks:
    shopping:
volumes:
    data:
    logs:
    node_modules: